namespace ESimConnect
{
  public static partial class SimVars
  {
    public static class Services
    {
      public const string BAGGAGELOADER_ANGLE_CURRENT = "BAGGAGELOADER ANGLE CURRENT";
      public const string BAGGAGELOADER_ANGLE_TARGET = "BAGGAGELOADER ANGLE TARGET";
      public const string BAGGAGELOADER_END_RAMP_Y = "BAGGAGELOADER END RAMP Y";
      public const string BAGGAGELOADER_END_RAMP_Z = "BAGGAGELOADER END RAMP Z";
      public const string BAGGAGELOADER_PIVOT_Y = "BAGGAGELOADER PIVOT Y";
      public const string BAGGAGELOADER_PIVOT_Z = "BAGGAGELOADER PIVOT Z";
      public const string BOARDINGRAMP_ELEVATION_CURRENT = "BOARDINGRAMP ELEVATION CURRENT";
      public const string BOARDINGRAMP_ELEVATION_TARGET = "BOARDINGRAMP ELEVATION TARGET";
      public const string BOARDINGRAMP_END_POSITION_Y = "BOARDINGRAMP END POSITION Y";
      public const string BOARDINGRAMP_END_POSITION_Z = "BOARDINGRAMP END POSITION Z";
      public const string BOARDINGRAMP_ORIENTATION_CURRENT = "BOARDINGRAMP ORIENTATION CURRENT";
      public const string BOARDINGRAMP_ORIENTATION_TARGET = "BOARDINGRAMP ORIENTATION TARGET";
      public const string BOARDINGRAMP_START_POSITION_Y = "BOARDINGRAMP START POSITION Y";
      public const string BOARDINGRAMP_START_POSITION_Z = "BOARDINGRAMP START POSITION Z";
      public const string CATERINGTRUCK_AIRCRAFT_DOOR_CONTACT_OFFSET_Z = "CATERINGTRUCK AIRCRAFT DOOR CONTACT OFFSET Z";
      public const string CATERINGTRUCK_ELEVATION_CURRENT = "CATERINGTRUCK ELEVATION CURRENT";
      public const string CATERINGTRUCK_ELEVATION_TARGET = "CATERINGTRUCK ELEVATION TARGET";
      public const string CATERINGTRUCK_OPENING_CURRENT = "CATERINGTRUCK OPENING CURRENT";
      public const string CATERINGTRUCK_OPENING_TARGET = "CATERINGTRUCK OPENING TARGET";
      public const string FUELTRUCK_HOSE_DEPLOYED = "FUELTRUCK HOSE DEPLOYED";
      public const string FUELTRUCK_HOSE_END_POSX = "FUELTRUCK HOSE END POSX";
      public const string FUELTRUCK_HOSE_END_POSZ = "FUELTRUCK HOSE END POSZ";
      public const string FUELTRUCK_HOSE_END_RELATIVE_HEADING = "FUELTRUCK HOSE END RELATIVE HEADING";
      public const string GROUNDPOWERUNIT_HOSE_DEPLOYED = "GROUNDPOWERUNIT HOSE DEPLOYED";
      public const string GROUNDPOWERUNIT_HOSE_END_POSX = "GROUNDPOWERUNIT HOSE END POSX";
      public const string GROUNDPOWERUNIT_HOSE_END_POSZ = "GROUNDPOWERUNIT HOSE END POSZ";
      public const string GROUNDPOWERUNIT_HOSE_END_RELATIVE_HEADING = "GROUNDPOWERUNIT HOSE END RELATIVE HEADING";
      public const string JETWAY_HOOD_LEFT_BEND = "JETWAY HOOD LEFT BEND";
      public const string JETWAY_HOOD_LEFT_DEPLOYMENT = "JETWAY HOOD LEFT DEPLOYMENT";
      public const string JETWAY_HOOD_RIGHT_BEND = "JETWAY HOOD RIGHT BEND";
      public const string JETWAY_HOOD_RIGHT_DEPLOYMENT = "JETWAY HOOD RIGHT DEPLOYMENT";
      public const string JETWAY_HOOD_TOP_HORIZONTAL = "JETWAY HOOD TOP HORIZONTAL";
      public const string JETWAY_HOOD_TOP_VERTICAL = "JETWAY HOOD TOP VERTICAL";
      public const string JETWAY_MOVING = "JETWAY MOVING";
      public const string JETWAY_WHEEL_ORIENTATION_CURRENT = "JETWAY WHEEL ORIENTATION CURRENT";
      public const string JETWAY_WHEEL_ORIENTATION_TARGET = "JETWAY WHEEL ORIENTATION TARGET";
      public const string JETWAY_WHEEL_SPEED = "JETWAY WHEEL SPEED";
      public const string MARSHALLER_AIRCRAFT_DIRECTION_PARKINGSPACE = "MARSHALLER AIRCRAFT DIRECTION PARKINGSPACE";
      public const string MARSHALLER_AIRCRAFT_DISTANCE = "MARSHALLER AIRCRAFT DISTANCE";
      public const string MARSHALLER_AIRCRAFT_DISTANCE_DIRECTION_X_PARKINGSPACE = "MARSHALLER AIRCRAFT DISTANCE DIRECTION X PARKINGSPACE";
      public const string MARSHALLER_AIRCRAFT_DISTANCE_DIRECTION_Z_PARKINGSPACE = "MARSHALLER AIRCRAFT DISTANCE DIRECTION Z PARKINGSPACE";
      public const string MARSHALLER_AIRCRAFT_ENGINE_SHUTDOWN = "MARSHALLER AIRCRAFT ENGINE SHUTDOWN";
      public const string MARSHALLER_AIRCRAFT_HEADING_PARKINGSPACE = "MARSHALLER AIRCRAFT HEADING PARKINGSPACE";
      public const string MARSHALLER_AIRCRAFT_PROJECTION_POINT_PARKINGSPACE = "MARSHALLER AIRCRAFT PROJECTION POINT PARKINGSPACE";
      public const string MARSHALLER_AIRCRAFT_VELOCITY = "MARSHALLER AIRCRAFT VELOCITY";
      public const string PUSHBACK_ANGLE = "PUSHBACK ANGLE";
      public const string PUSHBACK_ATTACHED = "PUSHBACK ATTACHED";
      public const string PUSHBACK_AVAILABLE = "PUSHBACK AVAILABLE";
      public const string PUSHBACK_CONTACTX = "PUSHBACK CONTACTX";
      public const string PUSHBACK_CONTACTY = "PUSHBACK CONTACTY";
      public const string PUSHBACK_CONTACTZ = "PUSHBACK CONTACTZ";
      public const string PUSHBACK_STATE__index = "PUSHBACK STATE:";
      public const string PUSHBACK_WAIT = "PUSHBACK WAIT";
      public const string WAGON_BACK_LINK_LENGTH = "WAGON BACK LINK LENGTH";
      public const string WAGON_BACK_LINK_ORIENTATION = "WAGON BACK LINK ORIENTATION";
      public const string WAGON_BACK_LINK_START_POSZ = "WAGON BACK LINK START POSZ";
      public const string WAGON_FRONT_LINK_LENGTH = "WAGON FRONT LINK LENGTH";
      public const string WAGON_FRONT_LINK_ORIENTATION = "WAGON FRONT LINK ORIENTATION";
      public const string WAGON_FRONT_LINK_START_POSZ = "WAGON FRONT LINK START POSZ";
    }
  }
}
